server:
  port: 8082
feign: # openfeign 远程调用 默认http客户端为HttpURLConnection不支持连接池，效率较低
  okhttp: # okhttp http客户端，支持连接池，效率较高
    enabled: true # 开启 okhttp 连接池
#======== nacos共享配置 ======================
# nacos配置中心的配置文件 读取以下参数
hm:
  db:
    database: hm-cart
  swagger:
    title: "黑马商城购物车服务接口文档"
    package: "com.hmall.cart.controller"

# 原始配置
#spring:
#  application:
#    name: cart-service # 微服务名称
#  profiles:
#    active: dev
#  datasource:
#    url: jdbc:mysql://${hm.db.host}:3306/hm-cart?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: ${hm.db.pw}
#  cloud:
#    nacos: # nacos服务注册发现
#      server-addr: 192.168.244.130:8848
#mybatis-plus:
#  configuration:
#    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
#  global-config:
#    db-config:
#      update-strategy: not_null
#      id-type: auto
#logging:
#  level:
#    com.hmall: debug
#  pattern:
#    dateformat: HH:mm:ss:SSS
#  file:
#    path: "logs/${spring.application.name}" # 生成的日志文件
#knife4j: # 丝袜哥配置 api文档
#  enable: true
#  openapi:
#    title: 黑马商城购物车管理接口文档
#    description: "黑马商城购物车管理接口文档"
#    email: zhanghuyi@itcast.cn
#    concat: 汐
#    url: https://www.itcast.cn
#    version: v1.0.0
#    group:
#      default:
#        group-name: default
#        api-rule: package
#        api-rule-resources:
#          - com.hmall.cart.controller
